window.TANK_IMAGES = [
  "50TP prototyp.png",
  "112.png",
  "AMX Canon d'assaut 105.png",
  "AMX M4 mle. 49.png",
  "Caernarvon Action X.png",
  "Chrysler K.png",
  "ELC EVEN 90.png",
  "FV4202.png",
  "HWK 30.png",
  "IS-6.png",
  "Kanonenjagdpanzer 105.png",
  "Löwe.png",
  "M4A1 Revalorisé.png",
  "M48A2 Räumpanzer.png",
  "Mauerbrecher.png",
  "Škoda T 27.png",
  "STA-2.png",
  "Strv S1.png",
  "T26E4 SuperPershing.png",
  "T26E5.png",
  "T-54 first prototype.png",
  "T92.png",
  "T-103.png",
  "WZ-120-1G FT.png"
];
